### ISSUE TITLE
Warning when missing extension for no member type

### ISSUE THREAD

**Issue by SanjulaGanepola** [IBM/sourceorbit#1]

**Comment by SanjulaGanepola** [comment]
@worksofliam How should we handle missing member types? Can we automatically detect it and fix this or just provide a warning?

**Comment by worksofliam** [comment]
@SanjulaGanepola Sorry it's so late. I think I am going to need more context on this issue

**Comment by SanjulaGanepola** [comment]
I don't quite remember what the issue was just looking at the title :confused:

@edmundreinhardt Any ideas?

**Comment by edmundreinhardt** [comment]
Yes, the issue was if the QSYS member did not have a member type (i.e. that field was blank on WRKMBRPDM) then sourceorbit choked on it.

**Comment by worksofliam** [comment]
> then sourceorbit choked on it.

What does this mean? It was ignored? It crashed?

**Comment by edmundreinhardt** [comment]
I would have to reproduce to be sure, but our hope was the SourceOrbit would flag these members and our sourcefiles with no file extension and the quick fix would be to prompt for a file extension.
