### ISSUE TITLE
No effect using the CLI in windows?

### ISSUE THREAD

**Issue by EASI-JHEI** [IBM/sourceorbit#19]
Hi,

First off, my thanks for this amazing intiative!
I was testing the software on my local Windows PC, using the example repository from this link: https://github.com/worksofliam/company_system

The installation of source orbit was no problem. But actually running the command seems to produce no output:
![image](https://github.com/IBM/sourceorbit/assets/92977422/ac41711d-7620-4638-86e5-99d2c75a5970)
![image](https://github.com/IBM/sourceorbit/assets/92977422/1f3478e9-14a1-479b-8a97-f6af5562db9a)

Maybe I'm using the tool incorrectly?
Running node version 20.9.0

Thanks

**Comment by worksofliam** [comment]
I am guessing that is true for now. We've really aimed at getting it work on IBM i and nix for now, but Windows support will be coming soon.

Though I am not sure why it wouldn't work on Windows right away.

**Comment by worksofliam** [comment]
Also I noticed you were using `-l`, try using just `so` or `so --verbose`!
