### ISSUE TITLE
Naming Structure not Compatible with IBM RDi 

### ISSUE THREAD

**Issue by priceaj** [IBM/sourceorbit#24]
The naming structure for members e.g. PGM1.PGM.RPGLE (https://codefori.github.io/docs/#/pages/developing/local/structure) is not compatible with RDi. 

RDi (using iProjects) will extract source objects using extensions such as .RPGLE .CLLE .CL .SQLRPGLE. These can then be committed to a git repository. However, source orbit requires a .PGM.RPGLE extension for a Program, adding these extensions breaks RDi iProjects, so it is not possible to use Source Orbit in an environment where RDi is deployed.  

Ideally developers should be able to select their own IDE and work directly from git. I myself will use both RDi and VSCode depending on the tasks I am trying to complete.  

Would it be possible to flag source as programs in some other way? e.g. a config file 

Alternatively, could you make some more intelligent default assumptions?

The messages below correctly identify that the below are Programs, not modules:
"Type detected as MODULE but Source Orbit doesn't support CL modules. Is it possible the extension should include '.pgm'?"
"type detected as MODULE but NOMAIN keyword was not found. Is it possible the extension should include '.pgm'?"

**Comment by edmundreinhardt** [comment]
I agree, this is specifically enabling BOB and Merlin and RDi will be adding support for BOB

**Comment by worksofliam** [comment]
You are both correct.

The cool part is that Source Orbit can be configured to support any extension. I am typing this on my phone, but the `.pgm` is actually configurable!

@priceaj check out `so --init` and see the resulting `iproj.json` changes.

**Comment by worksofliam** [comment]
@priceaj Quick update: ignore what I said about `--init` as it is only used when `-bf make` is used, as it controls how the `makefile` is generated.

**Comment by priceaj** [comment]
Oh fair enough, I didn't get a chance to test it out
