### ISSUE TITLE
SQL clause WITH is being added as a referenced object 

### ISSUE THREAD

**Issue by rbeckham** [IBM/sourceorbit#56]
Hi,
In my code I am writing a sql statement that has a WITH clause in it.  Source Orbit is picking this up as a object that is referenced.

```
exec sql declare c1 cursor for 
        with temp as (
          select
           field1,
           field2
          from table1
        )
Select * from temp;
```

Source orbit is throwing an error saying it cannot find the TEMP object....well this doesn't really exist.
I think in these cases SO will have to figure out that temp is used in connection to the WITH clause and will need to only consider objects inside the WITH clause as valid objects referenced.  In my example above, SO should only find TABLE1.

**Comment by worksofliam** [comment]
Release 0.10.4 with the fix and also created an additional test case for it.
