### ISSUE TITLE
Bring `iproj` support into base

### ISSUE THREAD

**Issue by worksofliam** [IBM/sourceorbit#60]
Right now, iproj support only exists in the makefile generation to get the list of include paths, but we actually need this in the base for include resolving.

**Comment by edmundreinhardt** [comment]
I wanted to meet with you on that.  I.e have the Code 4 i LSPs respect the includePath.  Thanks for being ahead of the curve again.

**Comment by worksofliam** [comment]
@edmundreinhardt Code for IBM i already supports `includePaths` in `iproj`! But, Source Orbit does not.

**Comment by worksofliam** [comment]
Closing as I didn't provide enough context here.

**Comment by AIforIBMi** [comment]
The issue is that the RPG (and COBOL etc) LSPs do not respect the includePath specified in the iproj.json
@worksofliam
