### ISSUE TITLE
Option to not use `.pgm` notation

### ISSUE THREAD

**Issue by worksofliam** [IBM/sourceorbit#61]
Right now, we are forcing projects to use the SO extension naming convention and make use of `.pgm`.

I'd like an option to ignore it, so users do not have to add `.pgm` all over the place. This means we will instead detect the object type based on the source code (`NOMAIN` in RPG, `main` in C, `PGM` in CL, etc)

**Comment by edmundreinhardt** [comment]
I am wondering if that is sufficient.  It is possible to be a module without using NOMAIN isn't it?

**Comment by edmundreinhardt** [comment]
I am warming up to this idea
