### ISSUE TITLE
.objrefs fails to ignore unresolved object when it is referenced multiple times in source

### ISSUE THREAD

**Issue by bmcpherson-srlife** [IBM/sourceorbit#67]
I have source which has two external files referenced to pull data from for validation. One is only referenced once (SYSCTL) in the source code while the other (USERCTL) is referenced three different times in the source code. I have listed both in the .objrefs file (see below) so the "No object found for reference" message will stop popping up.

```
# Files that exist outside this project

USERCTL.FILE
SYSCTL.FILE

```
However, I have noticed that only SYSCTL is no longer being mentioned in the "no reference" messages, but USERCTL is still showing up three times. But, the moment I comment out two of the three instances of USERCTL, the messages finally stop. I do not know if this is intended behavior, but I wanted to make mention of it. 

Thanks!

**Comment by bmcpherson-srlife** [comment]
Hi Liam, please see the included file. 

[source_example.zip](https://github.com/IBM/sourceorbit/files/15178244/source_example.zip)

It's probably worth another ticket, but the "so -bf bob" command produces a strange resulting Rules.mk file (also included, since it comes from the same source). 

Thanks!

**Comment by worksofliam** [comment]
Interestingly enough. I think it was an easy issue? Looks like there was a space at the end of the line. I will fix this so spaces are ignored correctly.

<img width="367" alt="image" src="https://github.com/IBM/sourceorbit/assets/3708366/f701bbaf-4183-40a7-9197-c53af8305b09">

**Comment by worksofliam** [comment]
Releasing in 0.10.3.

**Comment by bmcpherson-srlife** [comment]
Thank you for your hard work!
