### ISSUE TITLE
.objrefs not working

### ISSUE THREAD

**Issue by rbeckham** [IBM/sourceorbit#68]
I have the .objrefs file setup in my root directory and looks like this:
![image](https://github.com/IBM/sourceorbit/assets/6114419/c828176c-72d0-487b-b13a-db080e4c0b9d)

But I still get errors running the `so` command saying it cannot resolve the objects??
![image](https://github.com/IBM/sourceorbit/assets/6114419/548170b3-0513-480d-9ef8-8f9fcee47407)

**Comment by worksofliam** [comment]
@rbeckham any chance you can provide some source so I can create this?

**Comment by rbeckham** [comment]
@worksofliam Yes.  What I am working on is private code for a company but I will try to trim it down to something I can post to you

**Comment by rbeckham** [comment]
@worksofliam is there any way I can send you my project privately?
or if you show me how to debug the CLI code I don't mind to debug the code....just not exactly sure how to start the debug with it being a CLI.

**Comment by worksofliam** [comment]
@rbeckham yes, you may send me some code to `liama@thecompanyacronym.com` and I can take a look!

Debugging is easy, so feel free to also send me a meeting invite next week for 30 minutes and I can show you. Whatever works.

I will try and improve the docs for this.

**Comment by rbeckham** [comment]
@worksofliam is that the right email address? maybe I'm missing something.  when I send to that email it comes back and domain not found.

**Comment by worksofliam** [comment]
@rbeckham sent you my email on Twitter. Thanks.

**Comment by worksofliam** [comment]
@rbeckham I just pushed 0.10.3 which also just fixed an issue with the `.objrefs` file.

**Comment by rbeckham** [comment]
@worksofliams just sent my code to you.

**Comment by rbeckham** [comment]
@worksofliam I wanted to give a quick update.I had a chance to run through the debugging of the problem and it seems to be a timing issue I think here.

https://github.com/IBM/sourceorbit/blob/4f657a98ebab7cd2819bc9f44023514ad7381899/cli/src/targets.ts#L1205

When I run it step by step through the debugger, SourceOrbit works as expected which through my experience means a race issue.  I am trying to work through that now and will update when I can.

**Comment by worksofliam** [comment]
@rbeckham Thanks for the update. Let me know if I can help in any way.

**Comment by worksofliam** [comment]
@rbeckham Any progress or change here? A few releases have happened since July.

**Comment by rbeckham** [comment]
You can close this issue.  I never was able to consistently replicate the problem and it appears it was fixed I believe.
Thanks for checking in.

Ryan Beckham
I.T. Lead
McCreary Modern, Inc
