### ISSUE TITLE
Not Creating All Service Programs

### ISSUE THREAD

**Issue by Russ-illumifin** [IBM/sourceorbit#89]
I have a problem very similar with issue #76 where some of my service programs create while others do not. I have checked the code to make sure there are exports in the module source etc.

I think this message is the reason the service programs aren't being created:

Resolving modules for AN7000S.SRVPGM
QSRVSRC/an7000s.bnd - Removed as target because no modules were found with matching exports.

The module source has the same procedures exported that the binder language is expecting.

I have run SO with verbose and "so --bf json" output. I am attaching files for both of these outputs. I can provide some source if needed.

[Build JSON.txt](https://github.com/user-attachments/files/17317823/Build.JSON.txt)
[Build Verbose.txt](https://github.com/user-attachments/files/17317824/Build.Verbose.txt)

Maybe this is related to BOB because when I run so -bf bob it doesn't include the services programs in the Rules file. I manually add them to the Rules file and they still don't create.

**Comment by worksofliam** [comment]
Hey @Russ-illumifin - much like that other issue, a source example that can be recreated and shared would be fab so we can create a test fixture out of it. Sadly right now I can't seem to find the issue from navigating the JSON, but I'd like to be able to debug this.

**Comment by Russ-illumifin** [comment]
I will put the source together for you.

**Comment by Russ-illumifin** [comment]
@worksofliam I have the source ready in a zip file to send you. I need to send it to you privately because it is company code so please email me your email address. Once I hear from you via email, I will remove my email address from this post.

rroberts@insadminservices.com

**Comment by worksofliam** [comment]
@Russ-illumifin that is fab. You can reach me at `liama@thecompany.com` where `thecompany` is a three letter acronym. Thanks!

**Comment by Russ-illumifin** [comment]
@worksofliam, email sent.

**Comment by worksofliam** [comment]
@Russ-illumifin - thank you. I am traveling home today so it will be looked at first thing on Monday.

**Comment by worksofliam** [comment]
@Russ-illumifin I see you have sent me a bunch of .rpgle and .sqlrpgle, but no binder source. Any chance you can forward some over?

Also, is it specifically that `AN7000S` is not being listed in the build?

Thanks!

**Comment by Russ-illumifin** [comment]
Email sent this morning with files in QSRVSRC folder.

There are more than 50% of the service programs that don't create. I provided a list in the email.

**Comment by worksofliam** [comment]
I was able to identify the issue. It was rather simple, and I can't believe we didn't catch it sooner. Thanks for your test data @Russ-illumifin.

The fix will be out with 0.11.2.
