### ISSUE TITLE
if RPGLE include is in the same SRC-PF then `so -fi` does not fix

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/sourceorbit#9]
For some reason it does not detect included RPG files in the same SRC-PF as the include RPGLE.

My scenario found in https://github.com/edmundreinhardt/payroll-bob/commit/597e2e4f9f65f6106b195dd245f02d6af63528ad

**Comment by edmundreinhardt** [comment]
if you do `so -fi` it does not fix the `/include QRPGLESRC,ERRORTABLE` in `PAYROLL.pgm.RPGLE` line 36 to be `/include QRPGLESRC/ERRORTABLE`

**Comment by edmundreinhardt** [comment]
But if ERRORTABLE is in a different SRC-PF then it works

**Comment by worksofliam** [comment]
We fixed this together a few days ago! We also have a test case for it now.
