### ISSUE TITLE
When generating Rules.mk the include files are not on the dependency list

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/sourceorbit#94]
Rules.mk files are generated with the form
```Makefile
TARGET.MODULE: source.rpgle EXTFILE.FILE 
```
but they are missing dependency entries for include files.
For example if `source.rpgle` included `incme.rpgleinc` then the Rules.mk should have the form

```Makefile
TARGET.MODULE: source.rpgle incme.rpgleinc EXTFILE.FILE 
```

It is clear that source orbit knows about the include files, it simply needs to generate them in the dependency list.

**Comment by worksofliam** [comment]
I don't think we even collect a list of includes in Source Orbit. We need to grab them from the RPGLE parser I think. CL is the same.

**Comment by edmundreinhardt** [comment]
I though source orbit must know it, since it does the renaming of include files

**Comment by worksofliam** [comment]
It does know, but that info isn't available at the time of generating files.
