### ISSUE TITLE
Questions or problems

### ISSUE THREAD

**Issue by Russ-illumifin** [IBM/sourceorbit#95]
You all are doing great work on this tool! I really appreciate your efforts and being able to run Source Orbit within VSCode is very cool!

I probably shouldn't ask more than one question or problem in one issue but, here goes. I referred to the bob-recursive example build to create the files I thought would be needed. I also looked through the documentation of BOB and Sorce Orbit many times for answers but nothing I have tried works and some I just cannot find answers to.

Here are the questions/problems (if you want these in separate posts, I can do that):

1. I have multiple commands that don't get created and in the output of the build, none of them show as attempting to create. These commands are in the makefile file in the first level project folder.
2. How do I add modules to the APP binding directory? We have a handful of modules that get bound to programs and they don't get added to the APP binding directory. How can I do that? I know I can make them service programs (which I prefer), but I want to get this working as it is without changing more code.
3. How do I create my own binding directories? I found the example in the bob-recursive project and have the files I thought would create the binding directories, but they don't create. I would like to use the ones we have rather than relying on the APP one getting built each time.
4. I also attempted to override commands based upon what I read in the documentation but, would like more clarity on how to do that.
5. I found the object names in the Rules.mk file are case sensitive. Is that required or can that be changed so they are not case sensitive? I'm referring to the file and program names in the list after the name of the program being created. Example: 
    PRNTLETTRC.PGM: prntlettrc.pgm.clle PRNTLETTR2.PGM JOBLOGINS.PGM

I am attaching the build output, Rules.mk files, and makefile file, along with some folders with the code.

[Questions 2024-10-28.zip](https://github.com/user-attachments/files/17551090/Questions.2024-10-28.zip)

**Comment by worksofliam** [comment]
I have created #96 for the binding directory support.

**Comment by Russ-illumifin** [comment]
Thanks for the response, Liam. Some follow-up questions and comments.

1 (Commands don't create): The commands don't attempt to create (at least they don't show up in the build output). Some do have the same command processing program (CPP) name as the command. Maybe this is more of a BOB question too but the Rules.mk file has the command names and the CPP program names used when the command is created:
```
ANMAST01CL.CMD: anmast01cl.cmd ANMAST01CL.PGM 
ANMAST01CL.CMD: PGM=ANMAST01CL
ENDJOBLCK.CMD: endjoblck.cmd ENDJOBLCK.PGM
ENDJOBLOG.CMD: PGM=ENDJOBLCK
SNDFILE.CMD: sndfile.cmd SNDFILE.PGM
SNDFILE.CMD: PGM=SNDFILE
``` 

3 (Create binding directories). Is this more of a BOB thing too? The bob-recursive sample application has an example binding directory named SAMPLE that gets created when that build runs. I created a .BNDDIR file with the commands to run to create the binding directory along with the Rules.mk file.

```
/* Need to delete the BNDDIR, or it will always be older than the source */
/* because the CRTBNDDIR will fail the second time and only the ADDBNDDIRE is executed */     
!DLTOBJ OBJ(&O/&N) OBJTYPE(*BNDDIR)
CRTBNDDIR BNDDIR(&O/&N)
ADDBNDDIRE BNDDIR(&O/&N) +
   OBJ((PANMAST      *SRVPGM) +
(PANMAST2     *SRVPGM) +
(PSYSTEM      *SRVPGM))
```

4 (Command overrides): This may also be a BOB question because that is where I found the documentation (https://ibm.github.io/ibmi-bob/#/prepare-the-project/rules.mk?id=overriding-compile-settings). I was looking for a way to override command parameters such as the OPTION parm on the CRTSQLRPGI command. This is a parm that cannot be modified using the CHGCMDDFT command.

**Comment by worksofliam** [comment]
@Russ-illumifin Yes, there sounds like there is a lot of overlap between what SO does and what ibmi-bob does. It might be worth asking over in their repo too!

**Comment by edmundreinhardt** [comment]
### question 1
```
1 (Commands don't create): The commands don't attempt to create (at least they don't show up in the build output). Some do have the same command processing program (CPP) name as the command. Maybe this is more of a BOB question too but the Rules.mk file has the command names and the CPP program names used when the command is created:

ANMAST01CL.CMD: anmast01cl.cmd ANMAST01CL.PGM 
ANMAST01CL.CMD: PGM=ANMAST01CL
ENDJOBLCK.CMD: endjoblck.cmd ENDJOBLCK.PGM
ENDJOBLOG.CMD: PGM=ENDJOBLCK
SNDFILE.CMD: sndfile.cmd SNDFILE.PGM
SNDFILE.CMD: PGM=SNDFILE
```
@SanjulaGanepola we will need to reproduce this with the sample Russ provided earlier.  Just by eyeball, if `so` generated this, it seems to be valid and should work.

### Question 3
```
3 (Create binding directories). Is this more of a BOB thing too? The bob-recursive sample application has an example binding directory named SAMPLE that gets created when that build runs. I created a .BNDDIR file with the commands to run to create the binding directory along with the Rules.mk file.

/* Need to delete the BNDDIR, or it will always be older than the source */
/* because the CRTBNDDIR will fail the second time and only the ADDBNDDIRE is executed */     
!DLTOBJ OBJ(&O/&N) OBJTYPE(*BNDDIR)
CRTBNDDIR BNDDIR(&O/&N)
ADDBNDDIRE BNDDIR(&O/&N) +
   OBJ((PANMAST      *SRVPGM) +
(PANMAST2     *SRVPGM) +
(PSYSTEM      *SRVPGM))
```
Bob supports having pseudo source (CL) to create custom binding directories which are then referenced by other programs.
Source Orbit supports discovering binding relationships based examining the exports in the source.   
Liam has https://github.com/IBM/sourceorbit/issues/96 to track this.

**Comment by edmundreinhardt** [comment]
### Question 4
```
4 (Command overrides): This may also be a BOB question because that is where I found the documentation (https://ibm.github.io/ibmi-bob/#/prepare-the-project/rules.mk?id=overriding-compile-settings). I was looking for a way to override command parameters such as the OPTION parm on the CRTSQLRPGI command. This is a parm that cannot be modified using the CHGCMDDFT command.
```

@Russ-illumifin yes BOB support overwriting parameters on the compile command.  So for this example
```
FOO.MODULE:  foo.sqlrpgle
FOO.MODULE: OPTION = *EVENTF
```

**Comment by edmundreinhardt** [comment]
### Question 5
```
I found the object names in the Rules.mk file are case sensitive. Is that required or can that be changed so they are not case sensitive? I'm referring to the file and program names in the list after the name of the program being created. Example:
PRNTLETTRC.PGM: prntlettrc.pgm.clle PRNTLETTR2.PGM JOBLOGINS.PGM
```
Bob is built on gmake which is case sensitive.  However I do remember Tongkun writing code to detect the actual case of the  source file (first dependency, i.e. prntlettrc.pgm.clle above) and fixing it to the existing source file name in the generated source.  However for all of the other names, the case may matter.

**Comment by SanjulaGanepola** [comment]
> ### question 1
> ```
> 1 (Commands don't create): The commands don't attempt to create (at least they don't show up in the build output). Some do have the same command processing program (CPP) name as the command. Maybe this is more of a BOB question too but the Rules.mk file has the command names and the CPP program names used when the command is created:
> 
> ANMAST01CL.CMD: anmast01cl.cmd ANMAST01CL.PGM 
> ANMAST01CL.CMD: PGM=ANMAST01CL
> ENDJOBLCK.CMD: endjoblck.cmd ENDJOBLCK.PGM
> ENDJOBLOG.CMD: PGM=ENDJOBLCK
> SNDFILE.CMD: sndfile.cmd SNDFILE.PGM
> SNDFILE.CMD: PGM=SNDFILE
> ```
> 
> @SanjulaGanepola we will need to reproduce this with the sample Russ provided earlier. Just by eyeball, if `so` generated this, it seems to be valid and should work.

Hello @Russ-illumifin. I noticed you mentioned this issue here as well as in another issue in the bob-recursive-example repo. I do see that @edmundreinhardt provided some clarification to use `so -bf bob` instead of `so -bf make` to generate the Rules.mk files for Bob (https://github.com/IBM/bob-recursive-example/issues/18#issuecomment-2451905738). Did this resolve this problem?

As a side note, instead of using actions, you can also simply set the following build and compile commands in `iproj.json` to still generate the Rules.mk files and then run the Bob specific build/compile commands:

```json
  "buildCommand": "so -bf bob && makei build",
  "compileCommand": "so -bf bob && makei compile -f {filename}"
```

**Comment by Russ-illumifin** [comment]
@SanjulaGanepola I found that the commands were not creating because of another problem (SQL function not creating). When the SO command finished it created the commands that had command processing programs with the same name as the command but no others.

I put in an enhancement idea for a way to provide command creation parms which I think will work really well.

Thanks for the additional information as well on the build and compile commands. I'm wrapping my brain around these more each day and appreciate your insight.
